import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { GithubLogo, LinkedinLogo, Envelope, Article } from 'phosphor-react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const featured = [
    {
      title: 'OKCandles',
      description: 'description tbd',
      github: 'github link',
      demo: 'demolink',
      img: 'https://via.placeholder.com/400x200?text=Project+Image',
      technology: [
        'ReactJS',
        'React-Query',
        'Strapi'
      ]
    }, 
    {
      title: 'Portfolio',
      description: 'description tbd',
      github: 'github link',
      demo: 'demolink',
      img: 'https://via.placeholder.com/400x200?text=Project+Image',
      technology: [
        'ReactJS',
        'React-Query',
        'Strapi'
      ]
    }, 
  ]

  const projects = [
    {
      title: 'title', 
      description: 'description',
      github: 'github link'
    },   
    {
      title: 'title2', 
      description: 'description',
      github: 'github link'
    },
    {
      title: 'title3', 
      description: 'description',
      github: 'github link'
    }
  ]

  const work = [
    {
      title: 'Work',
      basis: 'Contractual',
      dates: '01-2020',
      img: 'https://via.placeholder.com/100x100?text=Project+Image'
    },
    {
      title: 'Work2',
      basis: 'Contractual',
      dates: '01-2020',
      img: 'https://via.placeholder.com/100x100?text=Project+Image'
    },
    {
      title: 'Work3',
      basis: 'Contractual',
      dates: '01-2020',
      img: 'https://via.placeholder.com/100x100?text=Project+Image'
    }
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Olena Pitcher Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <div className={styles.headerContainer_image}>
            <img src='/someimg.jng' alt='Portfolio Pic' width={300} height={300}/>
          </div>
          <div className={styles.headerContainer_content}>
            <h1>Olena Pitcher</h1>
            <span>Introvert</span>
            <p>
              I currently do not know how to do anything or be an asset to any company. Thanks for nothing. I do my best.
            </p>
            <div>
              <a href='/somelink.pdf' download>Download Resume</a>
            </div>
          </div>
        </section>

        <h2>Projects</h2>
        <section>
          {featured && featured.map(item => (
            <div>
              <div>
                <h3>{item.title}</h3>
                <p>{item.technology.toString()}</p>
                <p>{item.description}</p>
                <div>
                  <a href={item.github}>Github</a>
                  <a href={item.demo}>Demo</a>
                </div>
              </div>
              <div>
                <img src={item.img} alt='Project Image'/>
              </div>
            </div>
          ))}
        </section>

        <section>
          {projects && projects.map(item => (           
        <div>
          <h3>{item.title}</h3>
          <p>{item.description}</p>
          <div>
              <a href={item.github}>Github</a>
             </div>
            </div>
          ))}
        </section>

        <h2>Employment</h2>
        <section>
          {work && work.map(item => (
            <div>
              <img src={item.img} alt={item.title}/>
              <div>
                <h3>{item.title}</h3>
                <p>{item.basis}: {item.dates}</p>
              </div>
            </div>
          ))}
        </section>

        <section>
          
        </section>
      </main>

      <footer className={styles.footer}>
            <p>Olena Pitcher - Perry, UT</p>
            <div>
              <a href='https://www.github.com/OlenaMH'><GithubLogo size={24}/></a>
              <a href='https://www.linkedin.com'><LinkedinLogo size={24}/></a>
              <a href='mailto:olenamh@gmail.com'><Envelope size={24}/></a>
              <a href='/somelink.pdf' title= 'Resume Download' download><Article size={24}/></a>
            </div>
      </footer>
    </div>
  )
}

export default Home
